name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: Auto-assign Issue
              uses: pozil/auto-assign-issue@v1.11.0
              with:
                  assignees: lawnmowing-programmer/algorithm-study
                  abortIfPreviousAssignees: true
